spring.datasource.url=jdbc:postgresql:///prompt-box?cloudSqlInstance=rock-extension-484507-t6:asia-northeast3:postgres-18&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}
