spring.application.name=prompt-box

server.port=7070
server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=on_param

spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/prompt
spring.datasource.username=prompt
spring.datasource.password=@@8638prompt
spring.datasource.hikari.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
#spring.liquibase.url=jdbc:postgresql://localhost:5432/prompt
#spring.liquibase.user=prompt
#spring.liquibase.password=@@8638prompt

spring.threads.virtual.enabled=true

spring.jackson.default-property-inclusion=non_null

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
spring.autoconfigure.exclude=org.springdoc.core.configuration.SpringDocDataRestConfiguration,org.springdoc.core.configuration.SpringDocHateoasConfiguration

logging.pattern.console=%clr(%date{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5level}) %clr([%15.15thread]){faint} %clr(%-50.50logger{49}){yellow} %clr(%class.%method\\(%file:%line\\)){cyan} %clr(:){faint} %message%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
#logging.level.root=TRACE
logging.level.TRACER_LOG=INFO
#logging.level.okhttp3=TRACE
logging.level.com.openai=TRACE
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.liquibase=trace
